# Generated by Django 2.2.5 on 2019-09-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20190908_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='img',
            new_name='i',
        ),
    ]
