# Generated by Django 2.2.5 on 2019-09-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20190908_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='i',
            field=models.ImageField(upload_to='media'),
        ),
    ]
