# Generated by Django 2.2.5 on 2019-09-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_auto_20190908_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='i',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
