# Generated by Django 2.2.5 on 2019-09-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_auto_20190909_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='i',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
