# Generated by Django 2.2.5 on 2019-09-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='Name_of_Product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
