# Generated by Django 2.2.5 on 2019-09-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_project_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='u_id',
            field=models.IntegerField(null=True),
        ),
    ]
